version: '3.8'

services:
  flagd:
    image: ghcr.io/open-feature/flagd:latest
    container_name: flagd
    ports:
      - "8013:8013"  # Expose the HTTP API
    command: >
      start --sources='[{"uri":"https://appconfigdata.us-east-1.amazonaws.com","provider":"appconfig","applicationID":"${APP_ID}","environmentID":"${ENV_ID}","configurationProfileID":"${CONFIG_PROFILE_ID}"}]'
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - ENV_ID=$ENV_ID
      - APP_ID=$APP_ID
      - AWS_REGION=us-east-1
