name: Upload JSON to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Upload changed files to S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_UPLOAD_DIR: ${{ secrets.S3_UPLOAD_DIR }}
        run: |
          # If the repository has only one commit, use ls-files instead of git diff
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            FILES=$(git diff --name-only HEAD^ HEAD | grep 'data.json' || true)
          else
            FILES=$(git ls-files | grep 'data.json' || true)
          fi

          # Upload files if there are any changes
          if [[ -n "$FILES" ]]; then
            for file in $FILES; do
              aws s3api put-object --bucket "$S3_BUCKET" --key "$S3_UPLOAD_DIR/$(basename $file)" --body "$file"
            done
          else
            echo "No files to upload."
          fi
