name: Upload JSON to S3 and Sync to AppConfig

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Upload changed feature flag file to S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_UPLOAD_DIR: ${{ secrets.S3_UPLOAD_DIR }}
        run: |
          # If the repository has only one commit, use `git ls-files` instead of `git diff`
          if git rev-parse --verify HEAD^ >/dev/null 2>&1; then
            FILES=$(git diff --name-only HEAD^ HEAD | grep 'featureflag.json' || true)
          else
            FILES=$(git ls-files | grep 'featureflag.json' || true)
          fi

          # Upload only if there are changes
          if [[ -n "$FILES" ]]; then
            for file in $FILES; do
              aws s3 cp "$file" "s3://$S3_BUCKET/$S3_UPLOAD_DIR/$(basename $file)"
            done
          else
            echo "No feature flag changes detected."
          fi

      - name: Sync Feature Flag to AWS AppConfig
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_UPLOAD_DIR: ${{ secrets.S3_UPLOAD_DIR }}
          APP_ID: ${{ secrets.APP_ID }}
          CONFIG_PROFILE_ID: ${{ secrets.CONFIG_PROFILE_ID }}
          ENV_ID: ${{ secrets.ENV_ID }}
        run: |
          # Download the feature flag file from S3
          aws s3 cp "s3://$S3_BUCKET/$S3_UPLOAD_DIR/featureflag.json" featureflag.json

          # Upload the JSON to AWS AppConfig
          aws appconfig create-hosted-configuration-version \
            --application-id "$APP_ID" \
            --configuration-profile-id "$CONFIG_PROFILE_ID" \
            --content file://featureflag.json \
            --content-type "application/json"
