name: Upload JSON to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your AWS region

      - name: Upload changed files to S3
        run: |
          for file in $(git diff --name-only HEAD^ HEAD | grep 'data.json'); do
            aws s3api put-object --bucket ${{ secrets.S3_BUCKET }} --key ${{ secrets.S3_UPLOAD_DIR }}/$(basename $file) --body $file
          done
